### ISSUE TITLE
unused imports - flake8 ?

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#83]
During the process of transferring more examples using tfSlim from my lib to tensorpack, I noticed some python-style issues, e.g. unused imports. I know that these are not destroying any functionalities, but my editor is urging me to remove them.

Do you mind to include my `tox.ini` and `.travis.yml` from https://github.com/PatWie/tfblueprint. I would start removing some of these issues.

**Comment by ppwwyyxx** [comment]
Thanks! I'll run autopep8 and see what happens. My understanding is that it doesn't always do the right thing (?) so it might take some time to fix the style. It's modifying code everywhere so probably it's better I work on it.

I'll leave this open and we can look at the CI tools after existing style issues have been fixed.

**Comment by PatWie** [comment]
If you put these files

tox.ini

````ini
[tox]
envlist = py26,py27

[flake8]
max-line-length = 120
exclude = .git,__init__.py
````
into the root-dir, then "flake8 ." should give the same output as in


````YAML
language: "python"
python:
   - "2.7"
sudo: false
cache: pip

before_script:
  - pip install flake8
  - flake8 --version
script:
  - flake8 .

notifications:
  email: false
````
